apiVersion: v1
kind: Service
metadata:
  name: letsencrypt
  labels:
    app: letsencrypt
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: letsencrypt
